// <auto-generated />
using Data.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entitiy.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorImage = "trainer-1.jpg",
                            AuthorName = "Asdasd",
                            Category = "asdasd",
                            Content = "asdasd",
                            CoverImage = "course-1.jpg",
                            Name = "sdfsdf"
                        },
                        new
                        {
                            Id = 2,
                            AuthorImage = "trainer-1.jpg",
                            AuthorName = "Asdasd",
                            Category = "asdasd",
                            Content = "asdasd",
                            CoverImage = "course-1.jpg",
                            Name = "sdfsdf"
                        },
                        new
                        {
                            Id = 3,
                            AuthorImage = "trainer-1.jpg",
                            AuthorName = "Asdasd",
                            Category = "asdasd",
                            Content = "asdasd",
                            CoverImage = "course-1.jpg",
                            Name = "sdfsdf"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
